extract_path: J:/Projects/Assessor/extracts/2026/July_26
project_path: J:/Projects/Assessor/assessor_permit
juris_path: /gis/cities/cities_2025.shp
crs: 2285

kitsap_base_path: /kitsap/data/base_year/GIS/parcels_2009.shp
kitsap_current_path: /Kitsap/Tax_Parcel_lot_polygons_-628505606531791478.zip
kitsap_output_path: /kitsap/data/2026/GIS/parcels_2026_2010_region25_tract20.shp

pierce_base_path: /pierce/data/base_year/GIS/pierce_parcels_2012.shp
pierce_current_path: /Pierce/Tax_Parcels_-5399196296814840179.zip
pierce_output_path: /pierce/data/2026/GIS/parcels_2026_2012_region25_tract20.shp